const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui=document.querySelector('#ui'),start=document.querySelector('#start-screen'),pause=document.querySelector('#pause-screen'),touch=document.querySelector('#touch');
const hearts=document.querySelector('#hearts'),rupees=document.querySelector('#rupees'),keysEl=document.querySelector('#keys'),weaponEl=document.querySelector('#weapon-name'),ammoEl=document.querySelector('#weapon-ammo'),mini=document.querySelector('#mini'),msg=document.querySelector('#message');
const maps={overworld:["######################","#........#...........#","#........#...........#","#..T.....#....N......#","#........#...........#","####.#####....####.###","#.............#......#","#...###.......#......#","#...#.........#..K...#","#...#....T....#......#","#...#.........#####.##","#..............D.....#","#........###.........#","#........#...........#","#....H...#....T......#","#........#...........#","#........#..#####....#","#........#............","#....................#","#..........#####.....#","#....................#","######################"],dungeon:["####################","#......#...........#","#.####.#.#####.###.#","#.#....#.....#...#.#","#.#.####.###.#.#.#.#","#.#.....#...#...#.#","#.#####.#.#.#####.#.#","#.....#.#.#.....#...#","#.###.#.#.#####.#####","#...#.#.#.....#.....#","###.#.#.#####.#####.#","#...#.#.....#.....#.#","#.#.#.#####.#####.#.#","#.#.#.....#...#...#.#","#.#.#####.#.#.###.#.#","#.#.....#...#...#...#","#.#####.#####.#######","#......#...........B#","#...................#","####################"]};
const TILE=64,weapons={sword:['ESPADA','∞'],boomerang:['BOOMERANG','∞'],bow:['ARCO','∞'],bomb:['BOMBA','3'],candle:['VELA','∞'],rod:['VARITA','MAGIA']};
let state={mode:'overworld',running:false,paused:false,p:{x:2.5*TILE,y:2.5*TILE,a:0,hp:6,max:6},weapon:'sword',keys:0,rupees:0,inv:new Set(['sword']),items:[],enemies:[],shots:[],cool:0,flash:0,door:false,bossDead:false};
const held=new Set();let last=performance.now();
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();
function map(){return maps[state.mode]}function tile(x,y){let m=map(),tx=Math.floor(x/TILE),ty=Math.floor(y/TILE);return ty<0||ty>=m.length||tx<0||tx>=m[0].length?'#':m[ty][tx]}
function wall(x,y){let t=tile(x,y);return t==='#'||(state.mode==='overworld'&&t==='D'&&!state.door)}
function free(x,y){let r=12;return !wall(x-r,y-r)&&!wall(x+r,y-r)&&!wall(x-r,y+r)&&!wall(x+r,y+r)}
function resetWorld(){state.mode='overworld';state.p={x:2.5*TILE,y:2.5*TILE,a:0,hp:6,max:6};state.keys=0;state.rupees=0;state.inv=new Set(['sword']);state.weapon='sword';state.door=false;state.bossDead=false;state.items=[{x:3.4*TILE,y:3.4*TILE,k:'rupee'},{x:10.2*TILE,y:9.5*TILE,k:'rupee'},{x:5.1*TILE,y:14.8*TILE,k:'heart'},{x:15.8*TILE,y:8.4*TILE,k:'key'},{x:3.4*TILE,y:3.8*TILE,k:'boomerang'}];state.enemies=[['slime',7.4,7.1,3],['bat',15.2,5.4,2],['slime',11.4,15.2,3],['knight',17.5,14.7,5]].map(e=>({k:e[0],x:e[1]*TILE,y:e[2]*TILE,hp:e[3],max:e[3],dead:false,c:0}))}
function dungeon(){state.mode='dungeon';state.p.x=1.7*TILE;state.p.y=17.5*TILE;state.p.a=0;state.enemies=[['slime',5.3,16.1,3],['bat',9.2,14.1,2],['knight',13.2,11.2,5],['bat',17.1,4.8,2],['boss',17.3,17.6,20]].map(e=>({k:e[0],x:e[1]*TILE,y:e[2]*TILE,hp:e[3],max:e[3],dead:false,c:0}));state.items=[{x:6.2*TILE,y:3.6*TILE,k:'key'},{x:11.5*TILE,y:2.5*TILE,k:'bomb'},{x:3.5*TILE,y:15.4*TILE,k:'bow'},{x:8.1*TILE,y:7.3*TILE,k:'candle'},{x:13.7*TILE,y:5.4*TILE,k:'rod'}];say('Has entrado en la Fortaleza del Eclipse.')}
function say(t,ms=2200){msg.textContent=t;msg.style.opacity=1;clearTimeout(say.t);say.t=setTimeout(()=>msg.style.opacity=0,ms)}
function hud(){hearts.textContent='♥'.repeat(state.p.hp)+'♡'.repeat(state.p.max-state.p.hp);rupees.textContent=state.rupees;keysEl.textContent=state.keys;weaponEl.textContent=weapons[state.weapon][0];ammoEl.textContent=weapons[state.weapon][1];mini.textContent=state.mode==='overworld'?'PRADERAS · encuentra la puerta de piedra':'MAZMORRA · derrota al guardián'}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function ad(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b))}
function pickup(){for(let i=state.items.length-1;i>=0;i--){let it=state.items[i];if(dist(state.p,it)<30){state.items.splice(i,1);if(it.k==='rupee'){state.rupees+=5;say('+5 rupias')}else if(it.k==='heart'){state.p.hp=Math.min(state.p.max,state.p.hp+2);say('Corazón: recuperas vida')}else if(it.k==='key'){state.keys++;say('Has encontrado una llave')}else{state.inv.add(it.k);say('Nuevo objeto: '+weapons[it.k][0])}}}let t=tile(state.p.x,state.p.y);if(state.mode==='overworld'&&t==='D'&&!state.door&&state.keys){state.keys--;state.door=true;say('La puerta de piedra se abre')}else if(state.mode==='overworld'&&t==='D'&&state.door)dungeon()}
function move(dt){let f=(held.has('w')?1:0)-(held.has('s')?1:0),s=(held.has('d')?1:0)-(held.has('a')?1:0);let l=Math.hypot(f,s)||1;f/=l;s/=l;let sp=155*dt*(held.has('shift')?1.35:1),dx=(Math.cos(state.p.a)*f-Math.sin(state.p.a)*s)*sp,dy=(Math.sin(state.p.a)*f+Math.cos(state.p.a)*s)*sp;if(free(state.p.x+dx,state.p.y))state.p.x+=dx;if(free(state.p.x,state.p.y+dy))state.p.y+=dy}
function attack(){if(!state.running||state.paused||state.cool>0)return;state.cool=.35;let p=state.p;if(state.weapon==='sword'){state.enemies.forEach(e=>{if(!e.dead&&dist(p,e)<120&&Math.abs(ad(Math.atan2(e.y-p.y,e.x-p.x),p.a))<.8){e.hp-=2;if(e.hp<=0){e.dead=true;state.rupees+=2;say('Enemigo derrotado · +2 rupias')}}})}else if(state.weapon==='candle'){say('La llama ilumina las sombras')}else{state.shots.push({x:p.x,y:p.y,a:p.a,k:state.weapon,life:1.5})}}
function updateEnemies(dt){for(const e of state.enemies){if(e.dead)continue;e.c=Math.max(0,e.c-dt);let d=dist(state.p,e);if(d<260){let a=Math.atan2(state.p.y-e.y,state.p.x-e.x);let nx=e.x+Math.cos(a)*35*dt,ny=e.y+Math.sin(a)*35*dt;if(free(nx,ny)){e.x=nx;e.y=ny}}if(d<34&&e.c<=0){e.c=.8;state.p.hp=Math.max(0,state.p.hp-1);state.flash=.25}}}
function updateShots(dt){for(let i=state.shots.length-1;i>=0;i--){let s=state.shots[i];s.life-=dt;s.x+=Math.cos(s.a)*480*dt;s.y+=Math.sin(s.a)*480*dt;if(s.life<=0||wall(s.x,s.y)){state.shots.splice(i,1);continue}for(const e of state.enemies)if(!e.dead&&dist(s,e)<28){e.hp-=state.weapon==='bomb'?5:2;state.shots.splice(i,1);if(e.hp<=0){e.dead=true;state.rupees+=e.k==='boss'?20:2;say(e.k==='boss'?'¡GUARDIÁN DERROTADO!':'Golpe certero');}break}}}
function ray(a,max=900){for(let d=2;d<max;d+=3){let x=state.p.x+Math.cos(a)*d,y=state.p.y+Math.sin(a)*d;if(wall(x,y))return d}return max}
function render(){let w=canvas.width,h=canvas.height,half=h/2,fov=Math.PI/3;ctx.fillStyle='#6d7b72';ctx.fillRect(0,0,w,half);ctx.fillStyle='#20271d';ctx.fillRect(0,half,w,half);let step=2;for(let x=0;x<w;x+=step){let a=state.p.a-fov/2+(x/w)*fov,d=ray(a);let ca=d*Math.cos(a-state.p.a);let wh=Math.min(h*2,22000/Math.max(1,ca));let y=half-wh/2;let shade=Math.max(25,135-ca/7);ctx.fillStyle='rgb('+shade+','+(shade+12)+','+(shade-20)+')';ctx.fillRect(x,y,step,wh)}drawObjects(fov,h);drawWeapon(h)}
function proj(a,fov){return canvas.width/2+(a/(fov/2))*(canvas.width/2)}
function drawObjects(fov,h){let arr=[];for(const e of state.enemies)if(!e.dead)arr.push({d:dist(state.p,e),a:ad(Math.atan2(e.y-state.p.y,e.x-state.p.x),state.p.a),o:e,type:'e'});for(const it of state.items)arr.push({d:dist(state.p,it),a:ad(Math.atan2(it.y-state.p.y,it.x-state.p.x),state.p.a),o:it,type:'i'});arr.sort((a,b)=>b.d-a.d);for(const q of arr){if(Math.abs(q.a)>fov/2+.15)continue;let x=proj(q.a,fov),s=Math.min(h*.65,42000/q.d);ctx.save();ctx.translate(x,h/2+s*.25);if(q.type==='e'){ctx.fillStyle=q.o.k==='boss'?'#742c38':q.o.k==='knight'?'#7f8790':q.o.k==='bat'?'#5a3d71':'#5b914a';ctx.beginPath();ctx.ellipse(0,-s*.35,s*.25,s*.42,0,0,7);ctx.fill();ctx.fillStyle='#f5df9a';ctx.fillRect(-s*.1,-s*.43,s*.06,s*.06);ctx.fillRect(s*.04,-s*.43,s*.06,s*.06);ctx.fillStyle='#111';ctx.fillRect(-s*.27,-s*.88,s*.54,4);ctx.fillStyle='#d44b45';ctx.fillRect(-s*.27,-s*.88,s*.54*(q.o.hp/q.o.max),4)}else{let k=q.o.k;ctx.fillStyle=k==='heart'?'#e5534b':k==='rupee'?'#4dd5a5':'#ddc45e';ctx.font=s*.42+'px serif';ctx.textAlign='center';ctx.fillText(k==='heart'?'♥':k==='rupee'?'◆':'✦',0,0)}ctx.restore()}}
function drawWeapon(h){ctx.save();ctx.translate(canvas.width*.5,h*.92);ctx.rotate(state.cool>0?-.35:0);let k=state.weapon;ctx.fillStyle='#4b3221';ctx.fillRect(-12,-110,24,100);ctx.fillStyle=k==='sword'?'#d8dddd':k==='bow'?'#996039':k==='boomerang'?'#d1ad55':k==='bomb'?'#242722':k==='candle'?'#e8d69c':'#9270b5';if(k==='sword'){ctx.beginPath();ctx.moveTo(-16,-110);ctx.lineTo(0,-190);ctx.lineTo(16,-110);ctx.fill()}else{ctx.beginPath();ctx.arc(0,-105,34,0,7);ctx.fill()}ctx.restore()}
function cycle(n){let a=['sword','boomerang','bow','bomb','candle','rod'];let k=a[n];if(k&&state.inv.has(k)){state.weapon=k;hud()}else say('Objeto aún no encontrado')}
function startGame(){start.classList.add('hidden');ui.classList.remove('hidden');state.running=true;state.paused=false;resetWorld();hud();say('Explora el reino y encuentra la puerta de piedra');if('ontouchstart'in window)touch.classList.remove('hidden');canvas.requestPointerLock?.()}
document.querySelector('#start-btn').onclick=startGame;document.querySelector('#resume-btn').onclick=()=>{state.paused=false;pause.classList.add('hidden');canvas.requestPointerLock?.()};document.querySelector('#restart-btn').onclick=()=>{state.running=false;pause.classList.add('hidden');start.classList.remove('hidden')};
addEventListener('keydown',e=>{if(e.key==='Escape'){if(!document.querySelector('#inventory').classList.contains('hidden'))document.querySelector('#inventory').classList.add('hidden');else{state.paused=!state.paused;pause.classList.toggle('hidden',!state.paused);if(state.paused)document.exitPointerLock?.()}return}if(e.key==='Tab'){e.preventDefault();document.querySelector('#inventory').classList.toggle('hidden');return}held.add(e.key.toLowerCase());if(e.key>='1'&&e.key<='6')cycle(+e.key-1);if(e.key.toLowerCase()==='e')pickup()});addEventListener('keyup',e=>held.delete(e.key.toLowerCase()));canvas.onclick=()=>{if(state.running&&!state.paused)canvas.requestPointerLock?.()};addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&!state.paused)state.p.a+=e.movementX*.0024});canvas.onmousedown=attack;
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(state.running&&!state.paused){move(dt);pickup();updateEnemies(dt);updateShots(dt);state.cool=Math.max(0,state.cool-dt);state.flash=Math.max(0,state.flash-dt);render();hud();if(state.p.hp<=0){state.running=false;start.classList.remove('hidden');start.querySelector('h1').textContent='HAS CAÍDO'}}else if(state.running)render();if(state.flash){ctx.fillStyle='rgba(200,30,30,.2)';ctx.fillRect(0,0,canvas.width,canvas.height)}requestAnimationFrame(loop)}requestAnimationFrame(loop);resetWorld();hud();